#!/usr/bin/env python3
"""
Pipeline Trace Visualizer for RV64 6-Stage Pipeline
====================================================
Reads pipeline_trace.csv generated by CPURV64P6_Cycle and produces
a colour-coded heatmap showing pipeline activity, stalls, and flushes.

Usage:
    python plot_pipeline.py [pipeline_trace.csv] [--start CYCLE] [--count N] [--out FILE]

Defaults: reads pipeline_trace.csv, shows first 200 cycles, saves pipeline_heatmap.png
"""

import argparse
import csv
import sys

try:
    import matplotlib
    matplotlib.use('Agg')  # non-interactive backend
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import numpy as np
except ImportError:
    print("ERROR: matplotlib and numpy are required. Install with:")
    print("  pip install matplotlib numpy")
    sys.exit(1)


STAGES = ['PCGen', 'Fetch', 'Decode', 'Issue', 'Execute', 'Commit']
VALID_COLS = ['pcgen_valid', 'fetch_valid', 'id_valid', 'issue_valid', 'ex_valid', 'commit_valid']
STALL_COLS = ['stall_pcgen', 'stall_fetch', '', 'stall_issue', '', '']
PC_COLS = ['pc_pcgen', 'pc_fetch', 'pc_id', 'pc_issue', 'pc_ex', 'pc_commit']

# Colour legend
CLR_ACTIVE  = '#2ecc71'  # green  – active instruction
CLR_BUBBLE  = '#ecf0f1'  # light grey – bubble (invalid stage)
CLR_STALL   = '#f39c12'  # orange – stalled
CLR_FLUSH   = '#e74c3c'  # red    – flushed


def load_trace(path, start, count):
    rows = []
    with open(path, newline='') as f:
        reader = csv.DictReader(f)
        for r in reader:
            cycle = int(r['cycle'])
            if cycle < start:
                continue
            if len(rows) >= count:
                break
            rows.append(r)
    return rows


def build_matrix(rows):
    """Build a NxS matrix of colour codes (N=cycles, S=stages) and a text matrix of PCs."""
    n = len(rows)
    s = len(STAGES)
    matrix = np.zeros((n, s))  # 0=bubble, 1=active, 2=stall, 3=flush
    text_matrix = [['' for _ in range(s)] for _ in range(n)]

    for i, r in enumerate(rows):
        is_flush = int(r['flush'])
        for j in range(s):
            valid = int(r[VALID_COLS[j]])
            stall_col = STALL_COLS[j]
            is_stalled = int(r[stall_col]) if stall_col else 0
            pc_str = r[PC_COLS[j]]
            
            # Format PC to just show the last 4 hexdigits for compactness
            if pc_str.startswith('0x'):
                pc_short = pc_str[2:]
                if len(pc_short) > 4:
                    pc_short = pc_short[-4:]
                pc_str = pc_short
            elif pc_str == "0":
                pc_str = ""

            if is_flush:
                # On a flush cycle, mark stages that had valid instructions as flushed
                if valid:
                    matrix[i, j] = 3
                    text_matrix[i][j] = pc_str
                else:
                    matrix[i, j] = 0
            elif is_stalled:
                matrix[i, j] = 2
                text_matrix[i][j] = pc_str
            elif valid:
                matrix[i, j] = 1
                text_matrix[i][j] = pc_str
            else:
                matrix[i, j] = 0

    return matrix, text_matrix


def plot(matrix, text_matrix, rows, out_file):
    from matplotlib.colors import ListedColormap
    cmap = ListedColormap([CLR_BUBBLE, CLR_ACTIVE, CLR_STALL, CLR_FLUSH])

    n_cycles = matrix.shape[0]
    
    # Only render text overlays and expand height if cycles count is reasonably small
    render_text = n_cycles <= 200
    desired_height = max(4, n_cycles * 0.25) if render_text else max(4, n_cycles * 0.05)
    fig_height = min(desired_height, 100) # Cap height at 100 inches to prevent matplotlib crashes on 50k+ cycles
    fig, ax = plt.subplots(figsize=(10, fig_height))

    ax.imshow(matrix, aspect='auto', cmap=cmap, vmin=0, vmax=3,
              interpolation='none' if n_cycles > 1000 else 'nearest')

    # Add PC text annotations if cycle count is small enough
    if render_text:
        for i in range(n_cycles):
            for j in range(len(STAGES)):
                text = text_matrix[i][j]
                if text:
                    # Choose text color based on background (black on green/orange, white on red)
                    color = 'white' if matrix[i, j] == 3 else 'black'
                    ax.text(j, i, text, ha="center", va="center", color=color, fontsize=8, fontweight='bold')
    # Labels
    cycle_labels = [rows[i]['cycle'] for i in range(n_cycles)]
    ax.set_yticks(range(n_cycles))
    # Show every Nth label to avoid clutter
    step = max(1, n_cycles // 40)
    ax.set_yticklabels([cycle_labels[i] if i % step == 0 else '' for i in range(n_cycles)],
                       fontsize=6)
    ax.set_xticks(range(len(STAGES)))
    ax.set_xticklabels(STAGES, fontsize=9)
    ax.set_xlabel('Pipeline Stage')
    ax.set_ylabel('Cycle')
    ax.set_title('RV64 CVA6 6-Stage Pipeline – PCGen | Fetch | Decode | Issue | Execute | Commit')

    # Legend
    patches = [
        mpatches.Patch(color=CLR_ACTIVE, label='Active'),
        mpatches.Patch(color=CLR_BUBBLE, label='Bubble'),
        mpatches.Patch(color=CLR_STALL,  label='Stall'),
        mpatches.Patch(color=CLR_FLUSH,  label='Flush'),
    ]
    ax.legend(handles=patches, loc='upper right', fontsize=8)

    plt.tight_layout()
    plt.savefig(out_file, dpi=150)
    print(f"Saved heatmap to {out_file}")


def print_summary(rows):
    total = len(rows)
    stalls = sum(1 for r in rows if int(r['stall_issue']))
    flushes = sum(1 for r in rows if int(r['flush']))
    active = total - stalls - flushes
    print(f"\n=== Pipeline Trace Summary (window: {total} cycles) ===")
    print(f"  Active cycles:  {active} ({100*active/total:.1f}%)")
    print(f"  Stall cycles:   {stalls} ({100*stalls/total:.1f}%)")
    print(f"  Flush cycles:   {flushes} ({100*flushes/total:.1f}%)")
    print(f"  Efficiency:     {100*active/total:.1f}%")


def main():
    parser = argparse.ArgumentParser(description='Visualize RV64 6-stage pipeline trace')
    parser.add_argument('csv', nargs='?', default='pipeline_trace.csv',
                        help='Path to CSV trace file (default: pipeline_trace.csv)')
    parser.add_argument('--start', type=int, default=1,
                        help='Start cycle (default: 1)')
    parser.add_argument('--count', type=int, default=200,
                        help='Number of cycles to display (default: 200)')
    parser.add_argument('--out', default='pipeline_heatmap.png',
                        help='Output image file (default: pipeline_heatmap.png)')
    args = parser.parse_args()

    try:
        rows = load_trace(args.csv, args.start, args.count)
    except FileNotFoundError:
        print(f"ERROR: Could not find {args.csv}")
        print("Run the simulator first to generate the trace file.")
        sys.exit(1)

    if not rows:
        print("ERROR: No trace data found in the specified range.")
        sys.exit(1)

    print(f"Loaded {len(rows)} cycles from {args.csv}")
    print_summary(rows)

    matrix, text_matrix = build_matrix(rows)
    plot(matrix, text_matrix, rows, args.out)


if __name__ == '__main__':
    main()
